{
 "title": "网盘统计",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "今日概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "今日新增用户",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reg_time,$__interval),\n  count(id) AS \"用户数\"\nFROM x_user\nWHERE\n  $__timeFilter(reg_time)\nGROUP BY 1\nORDER BY $__timeGroup(reg_time,$__interval)"
    }
   ]
  },
  {
   "title": "时间段上传数据量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  sum(file_size) AS \"数据量\"\nFROM x_file_origin\nWHERE\n  $__timeFilter(create_time)\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  {
   "title": "时间段上传总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  count(id) AS \"上传数量\"\nFROM x_user_file\nWHERE\n  $__timeFilter(create_time)\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  {
   "title": "累积上传数据量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(file_size)\nFROM x_file_origin\nwhere\n  file_status = 0"
    }
   ]
  },
  {
   "title": "用户文件总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM x_user_file\nwhere\n  status = 0"
    }
   ]
  },
  {
   "title": "今日上传",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  count(id) AS \"上传数量\"\nFROM x_user_file\nWHERE\n  $__timeFilter(create_time)\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  {
   "title": "时间段新增用户数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reg_time,$__interval),\n  count(id) AS \"新增用户\"\nFROM x_user\nWHERE\n  $__timeFilter(reg_time)\nGROUP BY 1\nORDER BY $__timeGroup(reg_time,$__interval)"
    }
   ]
  },
  {
   "title": "时间段新增文件数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  count(id) AS \"文件数\"\nFROM x_file_origin\nWHERE\n  $__timeFilter(create_time)\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  {
   "title": "用户总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM x_user\nwhere\n  user_status = 0 or user_status = 2"
    }
   ]
  },
  {
   "title": "文件总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM x_file_origin\nwhere\n  file_status = 0"
    }
   ]
  },
  { "title": "数据统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "数据量统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  sum(file_size) AS \"数据量\"\nFROM x_file_origin\nWHERE\n  $__timeFilter(create_time) AND\n  file_status = 0\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  {
   "title": "上传统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  count(id) AS \"上传次数\"\nFROM x_user_file\nWHERE\n  $__timeFilter(create_time)\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  {
   "title": "用户新增统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reg_time,$__interval),\n  count(id) AS \"新增用户数\"\nFROM x_user\nWHERE\n  $__timeFilter(reg_time)\nGROUP BY 1\nORDER BY $__timeGroup(reg_time,$__interval)"
    }
   ]
  },
  {
   "title": "上传文件统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(create_time,$__interval),\n  count(id) AS \"文件数\"\nFROM x_file_origin\nWHERE\n  $__timeFilter(create_time) AND\n  file_status = 0\nGROUP BY 1\nORDER BY $__timeGroup(create_time,$__interval)"
    }
   ]
  },
  { "title": "上传明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "上传明细",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  user_file.file_name,\n  user_file.file_path,\n  user_file.is_dir,\n  file_origin.file_size,\n  user.nick_name,\n  date_format(user_file.create_time, '%Y-%m-%d %H:%i:%s') as create_time\nFROM\n  x_user_file user_file\nLEFT JOIN\n  x_file_origin file_origin\nON\n  user_file.origin_id = file_origin.id\nLEFT JOIN\n  x_user user\nON\n  user_file.user_id = user.id\n  AND (user.user_status = 0 OR user.user_status = 2)\nWHERE\n  user_file.status = 0\n  AND file_origin.file_status = 0\n  AND $__timeFilter(user_file.create_time)\nORDER BY user_file.create_time DESC"
    }
   ]
  },
  {
   "title": "用户注册明细",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  x_user.id,\n  x_user.username,\n  x_user.nick_name,\n  x_user.avatar,\n  date_format(x_user.reg_time, '%Y-%m-%d %H:%i:%s') as reg_time\nFROM\n  x_user x_user\nWHERE\n  (x_user.user_status = 0 OR x_user.user_status = 2)\n  AND $__timeFilter(x_user.reg_time)\nORDER BY x_user.reg_time DESC"
    }
   ]
  }
 ]
}