version: '3'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - '/usr/local/prometheus/conf:/etc/prometheus'
    ports:
      - "9090:9090"
